apiVersion: v1
kind: Service
metadata:
  name: fast-api-test-service
spec:
  # Usamos NodePort para poder acceder fácilmente desde nuestra máquina local (Minikube)
  type: NodePort 
  selector:
    app: fast-api-test
  ports:
    - port: 80       # El puerto del servicio
      targetPort: 8000 # El puerto que expone tu contenedor (definido en el Dockerfile)
      nodePort: 30007  # El puerto fijo en tu máquina local (debe estar entre 30000-32767)